server:
  port: 8086
  servlet:
    context-path: /authenticationService

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication_db
    username: root
    password: admin
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  application:
    name: authenticationService
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      id:
        new_generator_mappings: false
  rabbitmq:
    host:  localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka

security:
  jwt:
    token:
      secret_key: key_rp5
      expire_time: 300000 # 5 minutos


